name: Build image for Llama-3-8B-Chinese
on:
  workflow_dispatch:
  push:
    paths:
      - 'models/**'
      - '.github/workflows/Llama-3-8B-Chinese.yml'
    branches:
      - 'main'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Login to Aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_HUB_USERNAME }}
          password: ${{ secrets.ALI_HUB_PASSWORD }}

      - name: Build and push Docker images to ghcr.io and DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docSite/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/llama-3-8b-chinese:q4_k_m
            ghcr.io/${{ github.repository_owner }}/llama-3-8b-chinese:q4_k_m
            registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALI_HUB_USERNAME }}/llama-3-8b-chinese:q4_k_m
          build-args: |
            MODEL_URL=https://huggingface.co/zhouzr/Llama3-8B-Chinese-Chat-GGUF/resolve/main/Llama3-8B-Chinese-Chat.q4_k_m.GGUF
            PROMPT_FORMAT=llama-3-chat
            CONTEXT_SIZE=4096
